### ISSUE TITLE
Each iteration should have a fresh set of environment variables

### ISSUE THREAD

**Issue by patimen** [a85/Newman#128]
Currently, the environment variables set by one iteration will be carried over to the next iteration. Each iteration should have clean environment variables or you will see some strange behavior.

**Comment by abhijitkane** [comment]
The idea behind environment variables is a run-wide storage for key-value pairs. Clearing it after iterations or folders wouldn't make much sense.

You can use postman.clearEnvironmentVariables() to clear environment variables manually.
