### ISSUE TITLE
Data differences?

### ISSUE THREAD

**Issue by trinonsense** [a85/Newman#172]
What's the difference between [request data](https://github.com/a85/Newman/blob/master/src/responseHandlers/TestResponseHandler.js#L165) and [data file](https://github.com/a85/Newman/blob/master/src/responseHandlers/TestResponseHandler.js#L174)?

I wanted to separate out the request data from the collection file into its own file, and I thought the data file from the command argument would do that. it didn't work, so I couldn't figure out what the data file is for.

**Comment by trinonsense** [comment]
psych, found my [answer](https://github.com/a85/Newman/blob/master/src/runners/RequestRunner.js#L272)

but, still, the term `data` for both request data and data file is rather confusing

**Comment by a85** [comment]
Agree. Will be changed in an upcoming version.
