### ISSUE TITLE
Version 1.2.6 broke my build

### ISSUE THREAD

**Issue by greuze** [a85/Newman#173]
In version 1.2.4 it worked, for example:

            "totalPassFailCounts": {
                "pass": 4,
                "fail": 0
            },
            "testPassFailCounts": {
                "Status code is 400": {
                    "pass": 1,
                    "fail": 0
                },
                "Response code is 001": {
                    "pass": 1,
                    "fail": 0
                },
                "Response message is defined": {
                    "pass": 1,
                    "fail": 0
                },
                "Response time is less than 500ms": {
                    "pass": 1,
                    "fail": 0
                }
            },

but in version 1.2.6, every test passes and failed at the same time (but the aggregation is ok):

            "totalPassFailCounts": {
                "pass": 4,
                "fail": 0
            },
            "testPassFailCounts": {
                "Status code is 400": {
                    "pass": 1,
                    "fail": 1
                },
                "Response code is 001": {
                    "pass": 1,
                    "fail": 1
                },
                "Response message is defined": {
                    "pass": 1,
                    "fail": 1
                },
                "Response time is less than 500ms": {
                    "pass": 1,
                    "fail": 1
                }
            },

**Comment by abhijitkane** [comment]
We've just released v1.2.7, which should fix this.

**Comment by greuze** [comment]
Thank you very much, very fast fix!!
