### ISSUE TITLE
sugarjs support broken?

### ISSUE THREAD

**Issue by joholo** [a85/Newman#176]
Similar symptoms as in #107. This code works fine in Postman, but not when running in Newman.

    var resp = Object.extended(JSON.parse(responseBody));

results in exception

    EXCEPTION - TypeError: Object function Object() { [native code] } has no method 'extended'

**Comment by abhijitkane** [comment]
Is this in a pre-request script or a test?

**Comment by joholo** [comment]
It's a test.

**Comment by abhijitkane** [comment]
Sugar handles Objects differently than it does strings - we'll push a fix for this soon.

**Comment by joholo** [comment]
Great. I appreciate your prompt reply!

**Comment by abhijitkane** [comment]
This has been fixed in Newman v1.2.9. Can you confirm?

**Comment by joholo** [comment]
Tested 1.2.9. Fix looks good. Thanks!
