### ISSUE TITLE
JSON.parse fails on UTF8 response

### ISSUE THREAD

**Issue by NeilCross** [a85/Newman#179]
I'm running against a service which returns a utf-8 response with a BOM.  Whilst request.js will retrieve and return the string fine, the BOM is not removed before running tests. This causes a failure when the response body is used with JSON.parse method with the following error.

    EXCEPTION - SyntaxError: Unexpected token ?

Would it be possible provide a mechanism to specify to request.js the expected response encoding either by:
* a configuration option provided to Newman or
* setting the request.js encoding property by interpreting the Accept-Charset header of the request

**Comment by abhijitkane** [comment]
We'll add a configuration option in the next release.

**Comment by abhijitkane** [comment]
There's a -N/--encoding option in the latest version, where you can specify "utf8" as the response-encoding.

**Comment by NeilCross** [comment]
Oh epic, thanks team!
