### ISSUE TITLE
POSTMAN environment variables not available within a "test" script

### ISSUE THREAD

**Issue by dhoyt** [a85/Newman#182]
When running a collection and setting POSTMAN environmental variables within a "test", the environmental variables set within that "test" are not available to the "test".

var data = JSON.parse(responseBody);

var abc_names = data.abc.names;

for (var i=0; i < abc_names.length; i++) {
  postman.setEnvironmentVariable("abc_firstNames"+(i+1), abc_names[i].firstName);
}

if(abc_names.length > 0) {
   postman.setEnvironmentVariable("firstPerson", environment.abc_firstNames1); //<- This FAILS
}

This does not fail when running with the POSTMAN Collection runner.

**Comment by abhijitkane** [comment]
We'll push a fix for this in the next release.

**Comment by dhoyt** [comment]
Awesome ! ... thanks for the quick response and reply.
