### ISSUE TITLE
newman won't install on windows using npm

### ISSUE THREAD

**Issue by dhoyt** [a85/Newman#185]
This is what I am getting when trying to install newman via npm (node v0.10.36) ...

C:\Dev\cur-workspace\curmusic-platform\src\test\postman\regression\run_regressio
ns>npm install -g newman
-

> contextify@0.1.13 install C:\Users\Dick\AppData\Roaming\npm\node_modules\newma
n\node_modules\jsdom\node_modules\contextify
> node-gyp rebuild

C:\Users\Dick\AppData\Roaming\npm\node_modules\newman\node_modules\jsdom\node_mo
dules\contextify>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin
\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:64:11
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:108:15)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Dick\AppData\Roaming\npm\node_modules\newman\node_modules\
jsdom\node_modules\contextify
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
npm ERR! contextify@0.1.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.13 install script.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "newman"
npm ERR! cwd C:\Dev\cur-workspace\curmusic-platform\src\test\postman\regression\
run_regressions
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by abhijitkane** [comment]
Can you try updating node to 0.12? Windows users have reported issues while installing on an older version of Node.

**Comment by dhoyt** [comment]
Here is the output after installing node v0.12.0 ...

C:\Dev\cur-workspace\curmusic-platform\src\test\postman\regression\run_regressio
ns>node -v
v0.12.0

C:\Dev\cur-workspace\curmusic-platform\src\test\postman\regression\run_regressio
ns>npm install newman -g
-


> contextify@0.1.13 install C:\Users\Dick\AppData\Roaming\npm\node_modules\newma
n\node_modules\jsdom\node_modules\contextify
> node-gyp rebuild


C:\Users\Dick\AppData\Roaming\npm\node_modules\newman\node_modules\jsdom\node_mo
dules\contextify>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin
\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:64:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:99:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Dick\AppData\Roaming\npm\node_modules\newman\node_modules\
jsdom\node_modules\contextify
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "newman" "-g"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.13 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Dev\cur-workspace\curmusic-platform\src\test\postman\regression\
run_regressions\npm-debug.log

**Comment by abhijitkane** [comment]
Do you have Python installed? https://github.com/TooTallNate/node-gyp says you need Python 2.7.x to build node-gyp, which is one of the packages that Newman depends on.

**Comment by dhoyt** [comment]
I had the previous version of newman running WITHOUT Python being installed. 

Everytime I ran newman, it was sending multiple lines to the console saying to update to 1.2.12. I did a npm update newman -g  but that made no difference so I (mistakenly) uninstalled newman ... npm uninstall newman ... to see if I could then force a new install to the latest version. Since uninstalling newman, I have no been able to install it.

**Comment by abhijitkane** [comment]
That's weird - you can install an older version of newman, and ignore the upgrade notifications for now - 
`npm install newman@1.2.8` or 1.2.9

**Comment by goldcougar** [comment]
I had the same problem.  This is the solution (as newman now seems to use some modules, and those modules have new requirements)

Follow the instructions here, under Windows: https://github.com/TooTallNate/node-gyp
Requires Pyton, Visual Stuio, and .NET SDK.

**Comment by dhoyt** [comment]
How can I tell what version of newman is installed ?

**Comment by abhijitkane** [comment]
`newman --version `

**Comment by goldcougar** [comment]
newman -V

**Comment by dhoyt** [comment]
All is good now. Thanks all for your immediate responses !!!

**Comment by NeilCross** [comment]
Sorry guys, but is the ongoing resolution for windows here to:

- use an old version of newman, 
- or require a manual install of an old version of python + full VS express install?

Obviously neither seems optimal, but more importantly neither is documented in the readme.

I've seen the issue is closed, but is there any plan to improve this overall?  There's no way many devops teams will agree that all this setup is required for a http test runner, and developers don't want to be sitting on an old version of newman due to these requirements.

**Comment by luke-adams** [comment]
instructions from the Postman guys are available here:
http://blog.getpostman.com/2015/04/09/installing-newman-on-windows/

**Comment by NeilCross** [comment]
@luke-adams, I've forked the repo to remove the dependency on domjs by rolling back to domjs-nogyp.  I'd decided that on my CI machines, running an old version of node was less of an issue than the VS install.

Repo is here: https://github.com/NeilCross/Newman

I'm not currently planning on releasing it in npm (newman-nogyp anyone?) but will keep it up to date with Newman development while the tests keep passing. Installation instructions are at the top of the readme.

**Comment by luke-adams** [comment]
@NeilCross - thank you!  I'm just logging off for the day, but I will take a proper look in the morning.

**Comment by eppsilon** [comment]
In case it helps someone else, here is how I got newman installed on Windows with VS 2015 installed. YMMV; I don't know much about npm, maybe this is dumb and breaks things.

```
> cd /c/program files/nodejs/node_modules/npm/node_modules
> npm install node-gyp@latest
> cd ~
> GYP_MSVS_VERSION="2015" GYP_MSVS_OVERRIDE_PATH=1 npm install -g newman
```

Running `npm install -g newman` without updating the version of node-gyp bundled with npm results in an error saying something like "14.0 wasn't found in the dictionary". I found that the error comes from [this node-gyp Python module](https://github.com/TooTallNate/node-gyp/blob/master/gyp/pylib/gyp/MSVSVersion.py). The module in node-gyp 2.0.0+ includes VS 14.0 (a.k.a VS 2015), but the copy of node-gyp in npm's node_modules is version 1.0.3.

**Comment by mverma-va** [comment]
@NeilCross I installed the latest node.js and newman using the commend "npm install https://github.com/NeilCross/Newman-nogyp/archive/master.tar.gz" on windows. It shows newman got installed successfully. 
Now I am running newman command in git bash and it gives me some wonky error.

manishve@PC2359 ~
$ newman
c:\node_modules\newman\node_modules\jsdom-nogyp\lib\jsdom\level1\core.js:554
      Array.prototype.splice.call(this._childNodes, refChildIndex, 0, newChild
                             ^
TypeError: Cannot set property length of [object Object] which has only a getter

    at Object.core.Node.insertBefore (c:\node_modules\newman\node_modules\jsdom-
nogyp\lib\jsdom\level1\core.js:554:30)
    at Object.<anonymous> (c:\node_modules\newman\node_modules\jsdom-nogyp\lib\j
sdom\level2\events.js:314:20)
    at Object.proto.(anonymous function) [as insertBefore] (c:\node_modules\newm
an\node_modules\jsdom-nogyp\lib\jsdom\utils.js:23:26)
    at Object.core.Node.appendChild (c:\node_modules\newman\node_modules\jsdom-n
ogyp\lib\jsdom\level1\core.js:672:17)
    at c:\node_modules\newman\node_modules\jquery\dist\jquery.js:4006:18
    at c:\node_modules\newman\node_modules\jquery\dist\jquery.js:4026:3
    at module.exports (c:\node_modules\newman\node_modules\jquery\dist\jquery.js
:31:12)
    at Object.<anonymous> (c:\node_modules\newman\src\utilities\PreRequestScript
Processor.js:6:48)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

manishve@PC2359 ~

**Comment by NeilCross** [comment]
@mverma-va hey, the branch I made only supports older versions of node, as jsdom-nogyp stopped working with newer versions of node.  Try using node 0.10.36.

**Comment by venkat318** [comment]
Hi, 
I have successfully installed newman(globally npm install newman-global) as a npm module in windows. 
![newman installation](https://user-images.githubusercontent.com/13761410/49185809-e1f96d80-f330-11e8-9872-19082dff62f6.JPG)

and when I try to get the version(newman -v) of it I got the following error, Please help me to resolve this issue.
![newman error](https://user-images.githubusercontent.com/13761410/49185775-cc844380-f330-11e8-99a1-536055ec0ad6.JPG)
The node version that I am using is v10.14.0
