### ISSUE TITLE
No tests running in newman

### ISSUE THREAD

**Issue by andyofb** [a85/Newman#191]
I have a number of calls in my collection and most of these have at least 1 test. When I run in the collection runner in postman the test run fine. In newman all of the calls run and return the status code etc but no tests are being ran. I have updated to the latest version and have tried exporting the collection as a file as well as from the URL.

**Comment by abhijitkane** [comment]
Can you send your collection file / URL to help@getpostman.com? (Either the one you're using, or the simplest one that reproduces the problem)

**Comment by andyofb** [comment]
I believe I have found the issue. 
 EXCEPTION - SyntaxError: Unexpected token <

I have tracked this down to the JSON containing html characters

var data = JSON.parse(responseBody);

as part of that response I have:
"further_info": "<p>testing<\/p>",

Whats the best way to solve this?

**Comment by andyofb** [comment]
I have investigated further and removed the html. The error is still occuring. 

THIS FAILS
```javascript
"tests": "var data = JSON.parse(responseBody);\ntests[\"Status code is 200\"] = responseCode.code === 200;",
```

THIS WORKS
```javascript
"tests": "tests[\"Status code is 200\"] = responseCode.code === 200;",
```

**Comment by abhijitkane** [comment]
Can you add a `console.log(responseBody);` to the beginning of the test script and see what the console prints? If the response body isn't valid JSON, the .parse() call will fail.

**Comment by andyofb** [comment]
{"id":17}

**Comment by abhijitkane** [comment]
Hm..I'm not sure why that's a problem. Can you send the file/URL to help@getpostman.com?

**Comment by abhijitkane** [comment]
If the response is `{"id":17}`, and JSON.parse() is failing, it might be an encoding issue.

Version 1.2.13 of Newman has a command line option "-N, --encoding [encoding-type]". You can try the various options (ascii,utf8,utf16le,ucs2,base64,binary,hex) to see if it works.

**Comment by andyofb** [comment]
I have tried all of the encoding types. Still no luck

--encoding ascii
Iteration 1 of 1
    EXCEPTION - SyntaxError: Unexpected token <

 --encoding utf8
Iteration 1 of 1
    EXCEPTION - SyntaxError: Unexpected token <

--encoding utf16le
Iteration 1 of 1
    EXCEPTION - SyntaxError: Unexpected token ℼ

--encoding ucs2
Iteration 1 of 1
    EXCEPTION - SyntaxError: Unexpected token ℼ

--encoding base64
Iteration 1 of 1
    EXCEPTION - SyntaxError: Unexpected token P

--encoding binary
Iteration 1 of 1
    EXCEPTION - SyntaxError: Unexpected token <

--encoding hex
Iteration 1 of 1
    EXCEPTION - SyntaxError: Unexpected token c

**Comment by abhijitkane** [comment]
Is this happening only with one collection, or just with this one?

If you send me your environment file, I can try running the exact command you're using, but that will probably contain sensitive information.

I'll continue to investigate why this is happening.

**Comment by andyofb** [comment]
I have now sussed out the issue. Postman collection is using the browser sessions. So my response is not the same in newman as there is an HTML page being delivered. This is why it works in collection and not newman. Sorry for the confusion. Any idea how I can make a call to set an authenticated session?

**Comment by andyofb** [comment]
Right update on this. I have made a call to the login page with login credentials and this is working for the rest of the calls in the collection.
